# Generated by Django 3.2.6 on 2022-06-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_pic',
        ),
        migrations.AddField(
            model_name='post',
            name='seats',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='seats_taken',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='theater_height',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='theater_width',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='trailer_link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
