# Generated by Django 3.2.6 on 2022-06-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_movie_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='author',
            new_name='director',
        ),
        migrations.AddField(
            model_name='movie',
            name='country_year',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='slogan',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='stars',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
