# Generated by Django 3.2.6 on 2022-06-24 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 13, 59, 39, 803490)),
        ),
    ]
